CREATE TABLE EMPLOYEES (
  EMPLOYEE_ID NUMBER NOT NULL PRIMARY KEY,
  EMPLOYEE_NAME VARCHAR2(30),
  EMPLOYEE_SURNAME VARCHAR2(100),
  EMAIL VARCHAR2(100),
  PASSWORD VARCHAR2(100),
  PHONE VARCHAR2(20),
  SALARY NUMBER,
  POSITION VARCHAR2(100),
  HIRE_DATE DATE
);

CREATE TABLE CAFE_USERS(
  USER_ID NUMBER NOT NULL PRIMARY KEY,
  USER_NAME VARCHAR2(30),
  USER_SURNAME VARCHAR2(50),
  EMAIL VARCHAR2(50),
  PASSWORD VARCHAR2(50),
  USERNAME VARCHAR2(30),
  PHONE VARCHAR2(20),
  LAST_CONNECTION DATE
);

CREATE TABLE ORDERS(
  ORDERS_ID NUMBER NOT NULL PRIMARY KEY,
  USER_ID NUMBER,
  SHOP_ID NUMBER,
  ORDER_DATE DATE,
  ADDRESS VARCHAR2(100),
  ORDER_NAME VARCHAR2(50),
  ORDER_SURNAME VARCHAR2(100),
  TOTAL_PRICE NUMBER,
  ORDER_STATE VARCHAR2(30)
);

CREATE TABLE ORDERS_EMPLOYEES(
  EMPLOYEE_ID NUMBER,
  ORDERS_ID NUMBER
);

CREATE TABLE SHOPS(
  SHOP_ID NUMBER NOT NULL PRIMARY KEY,
  SHOP_NAME VARCHAR2(100),
  LOCATION VARCHAR2(50),
  ADDRESS VARCHAR2(100),
  PHONE VARCHAR2(20),
  EMAIL VARCHAR2(100)
);

CREATE TABLE SHOP_PRODUCTS(
  SHOP_ID NUMBER,
  PRODUCT_ID NUMBER
);

CREATE TABLE ORDER_DETAILS(
  ORDER_DETAILS_ID NUMBER NOT NULL PRIMARY KEY,
  ORDERS_ID NUMBER,
  PRODUCT_ID NUMBER,
  QUANTITY NUMBER
);

CREATE TABLE PRODUCTS(
  PRODUCTS_ID NUMBER NOT NULL PRIMARY KEY,
  PRODUCT_NAME VARCHAR2(20),
  PRODUCT_DESCRIPTION VARCHAR2(200),
  STOCK NUMBER,
  REVIEWS NUMBER,
  CATEGORY_ID NUMBER,
  PRICE FLOAT(126),
  IMAGE_URL VARCHAR2(300)
);

CREATE TABLE CATEGORIES(
  CATEGORY_ID NUMBER NOT NULL PRIMARY KEY,
  CATEGORY_NAME VARCHAR2(30)
);

CREATE TABLE SESSIONS(
  USER_ID NUMBER,
  TOKEN VARCHAR2(100)
);

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_SHOPID FOREIGN KEY (SHOP_ID) REFERENCES SHOPS(SHOP_ID);

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_USERID FOREIGN KEY (USER_ID) REFERENCES CAFE_USERS(USER_ID);

ALTER TABLE ORDERS_EMPLOYEES ADD CONSTRAINT FK_ORDERS_EMPLOYEES_EMPLOYEEID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE ORDERS_EMPLOYEES ADD CONSTRAINT FK_ORDER_EMPLOYEES_ORDERID FOREIGN KEY (ORDERS_ID) REFERENCES ORDERS(ORDERS_ID);

ALTER TABLE ORDER_DETAILS ADD CONSTRAINT FK_ORDER_DETAILS_ORDERID FOREIGN KEY (ORDERS_ID) REFERENCES ORDERS(ORDERS_ID);

ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_CATEGORYID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID);

ALTER TABLE SHOP_PRODUCTS ADD CONSTRAINT FK_SHOP_PRODUCTS_SHOPID FOREIGN KEY (SHOP_ID) REFERENCES SHOPS(SHOP_ID);

ALTER TABLE SHOP_PRODUCTS ADD CONSTRAINT FK_SHOP_PRODUCTS_PRODUCTID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCTS_ID);

ALTER TABLE SESSIONS ADD CONSTRAINT FK_SESSIONS_USERID FOREIGN KEY (USER_ID) REFERENCES CAFE_USERS(USER_ID);

INSERT INTO CAFE_USERS (
  USER_ID,
  USER_NAME,
  USER_SURNAME,
  EMAIL,
  PASSWORD,
  USERNAME,
  PHONE,
  LAST_CONNECTION
) VALUES (
  1,
  'admin',
  'admin',
  'admin@gmail.com',
  '6ReAz3LV9B8M',
  'admin',
  NULL,
  NULL
);

INSERT INTO SESSIONS (
  USER_ID,
  TOKEN
) VALUES (
  1,
  '6d405aec62e3a170591c24736b7cbbc8'
)