create or replace TRIGGER CAFE_USERS_TRG 
BEFORE INSERT ON CAFE_USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.USER_ID IS NULL THEN
      SELECT CAFE_USERS_SEQ8.NEXTVAL INTO :NEW.USER_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

create or replace TRIGGER CATEGORIES_TRG 
BEFORE INSERT ON CATEGORIES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CATEGORY_ID IS NULL THEN
      SELECT CATEGORIES_SEQ8.NEXTVAL INTO :NEW.CATEGORY_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

create or replace TRIGGER EMPLOYEES_TRG 
BEFORE INSERT ON EMPLOYEES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.EMPLOYEE_ID IS NULL THEN
      SELECT EMPLOYEES_SEQ8.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

create or replace TRIGGER ORDER_DETAILS_TRG 
BEFORE INSERT ON ORDER_DETAILS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ORDER_DETAILS_ID IS NULL THEN
      SELECT ORDER_DETAILS_SEQ6.NEXTVAL INTO :NEW.ORDER_DETAILS_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

create or replace TRIGGER ORDERS_EMPLOYEES_TRG 
BEFORE INSERT ON ORDERS_EMPLOYEES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.EMPLOYEE_ID IS NULL THEN
      SELECT ORDERS_EMPLOYEES_SEQ4.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

create or replace TRIGGER ORDERS_TRG 
BEFORE INSERT ON ORDERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ORDERS_ID IS NULL THEN
      SELECT ORDERS_SEQ8.NEXTVAL INTO :NEW.ORDERS_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

create or replace TRIGGER PRODUCTS_TRG 
BEFORE INSERT ON PRODUCTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PRODUCTS_ID IS NULL THEN
      SELECT PRODUCTS_SEQ8.NEXTVAL INTO :NEW.PRODUCTS_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

create or replace TRIGGER SESSIONS_TRG 
BEFORE INSERT ON SESSIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.USER_ID IS NULL THEN
      SELECT SESSIONS_SEQ6.NEXTVAL INTO :NEW.USER_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

create or replace TRIGGER SHOP_PRODUCTS_TRG 
BEFORE INSERT ON SHOP_PRODUCTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SHOP_ID IS NULL THEN
      SELECT SHOP_PRODUCTS_SEQ4.NEXTVAL INTO :NEW.SHOP_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

create or replace TRIGGER SHOPS_TRG 
BEFORE INSERT ON SHOPS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SHOP_ID IS NULL THEN
      SELECT SHOPS_SEQ8.NEXTVAL INTO :NEW.SHOP_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;